
package cn.edu.nsu.aaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenAAA", targetNamespace = "http://aaa.nsu.edu.cn/", wsdlLocation = "http://aaa.nsu.edu.cn/NSUAAAWS/OpenAAA.asmx?WSDL")
public class OpenAAA
    extends Service
{

    private final static URL OPENAAA_WSDL_LOCATION;
    private final static WebServiceException OPENAAA_EXCEPTION;
    private final static QName OPENAAA_QNAME = new QName("http://aaa.nsu.edu.cn/", "OpenAAA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aaa.nsu.edu.cn/NSUAAAWS/OpenAAA.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENAAA_WSDL_LOCATION = url;
        OPENAAA_EXCEPTION = e;
    }

    public OpenAAA() {
        super(__getWsdlLocation(), OPENAAA_QNAME);
    }

    public OpenAAA(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENAAA_QNAME, features);
    }

    public OpenAAA(URL wsdlLocation) {
        super(wsdlLocation, OPENAAA_QNAME);
    }

    public OpenAAA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENAAA_QNAME, features);
    }

    public OpenAAA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenAAA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenAAASoap
     */
    @WebEndpoint(name = "OpenAAASoap")
    public OpenAAASoap getOpenAAASoap() {
        return super.getPort(new QName("http://aaa.nsu.edu.cn/", "OpenAAASoap"), OpenAAASoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenAAASoap
     */
    @WebEndpoint(name = "OpenAAASoap")
    public OpenAAASoap getOpenAAASoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://aaa.nsu.edu.cn/", "OpenAAASoap"), OpenAAASoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENAAA_EXCEPTION!= null) {
            throw OPENAAA_EXCEPTION;
        }
        return OPENAAA_WSDL_LOCATION;
    }

}
